Imports System.ComponentModel.DataAnnotations.Schema
Imports System.Data.Entity.ModelConfiguration

Public Class CustomerConfiguration
    Inherits EntityTypeConfiguration(Of Customer)

    Public Sub New()
        Me.HasKey(Function(c) c.CustomerId)

        ' Name is optional, max length 100
        Me.Property(Function(c) c.Name).
            HasMaxLength(100).
            IsOptional()

        ' Email is optional, max length 255
        Me.Property(Function(c) c.Email).
            HasMaxLength(255).
            IsOptional()

        ' Contact Number is optional, max length 15
        Me.Property(Function(c) c.ContactNumber).
            HasMaxLength(15).
            IsOptional()

        ' CreatedAt is required and auto-generated by database
        Me.Property(Function(c) c.CreatedAt).
            IsRequired().
            HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)

        ' Foreign Key: Customer has an optional Order
        Me.HasRequired(Function(c) c.Order).
            WithMany().
            HasForeignKey(Function(c) c.OrderId).
            WillCascadeOnDelete(True) ' 👈 Cascade delete when customer is deleted
    End Sub
End Class
